config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :applicants
  devise_for :employers

  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'

  resources :jobs
  root "jobs#index"
  get "employers/show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employer
  has_rich_text :description
  has_one_attached :image
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_employer!


  # GET /jobs or /jobs.json
  def index
      @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    @job.employer_id = current_employer.id 
    respond_to do |format|
      if @job.save
        AddJobWorker.perform_async
        Publisher.publish("jobs", @job.attributes)
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :company, :location, :salary, 
        :format,  :description, :level, :skill, :currency, :contact, :employer_id, :image)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col">
      
     <div class="card" style="width: 18rem;">
     <div class="card-body">
    <h5 class="card-title">Разместить вакансию</h5>
    <p class="card-text">Размещение всех вакансий 
    на сайте — бесплатное. Если у вас возникли трудности — напишите нам в Телеграме.</p>
    <button type="button" class="btn btn-warning"> <a href='https://t.me/topkekeu' target='blank'>
            СВЯЗАТЬСЯ</a> </button>
     </div>
     </div>

      </div>

  <div class="col-9"> 
    <div class="field">
    <p><b>Должность</b><p>
    <%= form.text_field :title %>
    </div>

  <div class="field">
    <p><b>Компания</b><p>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <p><b>Зарплата</b><p>
    <%= form.number_field :salary %>  <b>Валюта</b>
    <%= form.text_field :currency %>
  </div>

    <div class="field">
   
  </div>

  <div class="field">
    <p><b>Локация</b><p>
    <%= form.text_field :location %>
  </div>

   <div class="field">
    <p><b>Описание вакансии</b><p>
    <%= form.rich_text_area :description %>
  </div>

  <div class="field">
    <p><b>Уровень компетенции:</b><p>
    <%= form.text_field :level %>
  </div>

  <div class="field">
    <p><b>Тип занятости</b><p>
    <%= form.text_field :format %>
  </div>

  <div class="field">
  <p><b>Основной навык</b><p>
    <%= form.text_field :skill %>
  </div>

  <div class="field">
    <p><b>Контактная информация</b><p>
    <%= form.text_area :contact %>
  </div>

  <%= form.label :image %>
<%= form.file_field :image %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>
</div>

app/views/jobs/_header.html.erb
  <div class="container">
  <div class="row">
    <div class="col order-first">
    <li><%= link_to 'Домой', root_path %></li>
    </div>

    <div class="col">
    <% if employer_signed_in? %>
      <li><%= link_to 'Выйти', destroy_employer_session_path,
              method: :delete %></li>
    <% else %>
       <% unless applicant_signed_in? %>
      <li><%= link_to 'Войти как работодатель', new_employer_session_path %></li>
      <li><%= link_to 'Регистрация работодателя',
              new_employer_registration_path %></li> 
      <% end %>             
    <% end %>
    </div>

    <div class="col order-last">
    
    <% if applicant_signed_in? %>
      <li><%= link_to 'Выйти', destroy_applicant_session_path,
              method: :delete %></li>
    <% else %>
      <% if not employer_signed_in? %> 
      <li><%= link_to 'Войти как соискатель', new_applicant_session_path %></li>

      <li><%= link_to 'Регистрация соискателя',
              new_applicant_registration_path %></li>
       <% end %>      
    <% end %>
    </div>
    


</div>      
</div>

app/views/jobs/_job.html.erb
<div align='center'>

<div class="card w-50 text-center">
  <div class="card-body">
    <h3 class="card-title"><%= link_to job.title, job_path(job) %></h3>
    <h3><span class="badge bg-light text-dark"><%= job.salary %> <%= job.currency %> </span>
    <span class="badge  bg-light text-dark"><%= job.format %> </span>
    <span class="badge  bg-light text-dark"><%= job.location %></span>
    <p><%= job.created_at %></p><p>

 </div>
</div>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<%= render partial: 'employers/menu' %>

<div style="text-align:center;">
<h1>Вакансии для IT инженеров</h1>

<% if employer_signed_in? %>
Logged in as <strong><%= current_employer.email %></strong>.
<p>
<div>
</div>
<% end %>
<p>
<div class="row buffer-bottom">
  <%= render partial: 'jobs/job', collection: @jobs %>
</div>


</div>

app/views/jobs/new.html.erb
<%= render partial: 'employers/menu' %>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<%= render partial: 'employers/menu' %>
      
      <div class='container' >

      <%= image_tag @job.image %>

        <div class="col-md-12 bg-light p-3 border" text-align:left >
          <div text-align: center>
            <h3><%= @job.title %></h3>
            <p>Разместил работодатель: <%= @job.employer.email %></p>
            <p>Название компании: <%= @job.company %></p>
            <p>
              <h4><span class="badge  bg-light text-dark"><%= @job.location %></span>
              <span class="badge  bg-light text-dark"><%= @job.format %> </span>
              <span class="badge bg-light text-dark"><%= @job.salary %> <%= @job.currency %> </span>
              </h4>
            <p><h4>Описание вакансии</h4><p>
            <p><%= @job.description %></p>

            <div> 
            <p><h4>Контактная информация</h4><p>
            <p><%= @job.contact %></p>
          </div>
<p>
          <% if current_employer_can_edit?(@job) %>
          <div class="buffer-top">
            <%= link_to 'Изменить', edit_job_path(@job),
              class: 'btn btn-light' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  
      