config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :applicants
  devise_for :employers

  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'

  resources :jobs
  root "jobs#index"
  get "employers/show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employer.rb
class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         :confirmable

  has_many :jobs

  pay_customer stripe_attributes: :stripe_attributes

  def stripe_attributes(pay_customer)
    {
      address: {
        city: pay_customer.owner.city,
        country: pay_customer.owner.country
      },
      metadata: {
        pay_customer_id: pay_customer.id,
        user_id: id        
      }
    }
  end  

end

app/controllers/employers/confirmations_controller.rb
# frozen_string_literal: true

class Employers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employers/employers_controller.rb
class EmployersController < ApplicationController

def show
end

def create
  user = Employer.find(1)
  EmployersMailer.welcome_email(employer.id).deliver_later
end

end

app/controllers/employers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employers/passwords_controller.rb
# frozen_string_literal: true

class Employers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employers/registrations_controller.rb
# frozen_string_literal: true

class Employers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employers/sessions_controller.rb
# frozen_string_literal: true

class Employers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employers/unlocks_controller.rb
# frozen_string_literal: true

class Employers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/employers/_menu.html.erb
  
<div class="container" style="text-align:center;">
  <div class="row">
    <div class="col order-first">
    <li><%= link_to 'Домой', root_path %></li>
    </div>

    <div class="col">
    <% if employer_signed_in? %>
      <li><%= link_to 'Выйти', destroy_employer_session_path,
              method: :delete %></li>
    <% else %>
       <% unless applicant_signed_in? %>
      <li><%= link_to 'Войти как работодатель', new_employer_session_path %></li>
      <li><%= link_to 'Регистрация работодателя',
              new_employer_registration_path %></li> 
      <% end %>             
    <% end %>
    </div>

    <div class="col order-last">
    
    <% if applicant_signed_in? %>
      <li><%= link_to 'Выйти', destroy_applicant_session_path,
              method: :delete %></li>
    <% else %>
      <% if not employer_signed_in? %> 
      <li><%= link_to 'Войти как соискатель', new_applicant_session_path %></li>

      <li><%= link_to 'Регистрация соискателя',
              new_applicant_registration_path %></li>
       <% end %>      
    <% end %>
    </div>
  </div>      
</div>

  <div style="text-align:center;">
  <%= link_to 'Создать вакансию', new_job_path, class: 'btn btn-warning .btn-lg' %>
  <%= link_to 'Купить премиум', checkout_path, class: 'btn btn-light .btn-lg' %>
  </div>

app/views/employers/show.html.erb
<div class="text-center">
  <h1><%= @employer.email %></h1>

  <p class="buffer-top">
  <%= link_to "Редактировать профиль", edit_employer_path(@employer),
    class: 'btn btn-default' %>
  </p>

  <div class="row">
  <div class="col-md-12">
    <% if @employer.vacancies.any? %>
      <h3>Разместил вакансии:</h3>
      <div class="row">
        <%= render partial: 'jobs/job', collection: @employer.jobs %>
      </div>
    <% else %>
      <p class="buffer-top">Работодатель пока не создал ни одной вакансии</p>
    <% end %>
  </div>
</div>
</div>